FROM ruby:2.7.0-alpine3.11

# rails dependencies
RUN apk update \
  && apk upgrade \
  && apk add --update --no-cache \
  build-base curl curl-dev git postgresql-dev \
  yaml-dev zlib-dev nodejs yarn tzdata imagemagick \
  && gem install bundler

# phantomjs
WORKDIR /tmp
RUN apk add --update --no-cache curl &&\
  cd /tmp && curl -Ls https://github.com/dustinblackman/phantomized/releases/download/2.1.1/dockerized-phantomjs.tar.gz | tar xz &&\
  cp -R lib lib64 / &&\
  cp -R usr/lib/x86_64-linux-gnu /usr/lib &&\
  cp -R usr/share/fonts /usr/share &&\
  cp -R etc/fonts /etc &&\
  curl -k -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar -jxf - &&\
  cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs &&\
  rm -rf /tmp/*

# chrome headless
RUN apk update && apk add --no-cache nmap && \
  echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
  echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
  apk update && \
  apk add --no-cache \
  chromium \
  harfbuzz \
  "freetype>2.8" \
  ttf-freefont \
  nss

# config app home path
ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# install ruby dependencies
ADD ./tooli/Gemfile* $APP_HOME/
RUN bundle install

# install node dependecies
ADD ./tooli $APP_HOME
RUN yarn install --check-files